apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-rollout
  namespace: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}          # Pause indefinitely until resumed manually
      - setWeight: 40
      - pause: {duration: "10s"}
      - setWeight: 60
      - pause: {duration: "10s"}
      - setWeight: 80
      - pause: {duration: "10s"}
